<h1>GE: Midnight Data Science Madness  -- Team NoName

In [206]:
import numpy as np
from sklearn.cross_validation import train_test_split
import pandas as pd
from sklearn.preprocessing import normalize

<h4>Import and normalize data feature wise

In [207]:
data=pd.read_csv("~/Downloads/TRAININGFILE_HackGSU_MidnightMadness.csv")
#data=pd.read_csv("/Users/rajkirangaddati/Documents/Submission File.csv")

In [208]:
X=data[[u'GDP Per Capita (USD)', u'Youth unemployment rate (%)',
       u'Energy Production (Quadrillion Btu)',
       u'High-technology exports (current US$)']].values

In [209]:
y=data[[u'Electric power consumption (kWh per capita)']].values

In [210]:
normalize(X, norm='l2', axis=0, copy=False)

array([[  3.12367459e-02,   6.57080154e-02,   3.48915991e-02,
          3.14077081e-03],
       [  2.81080856e-02,   7.38536368e-02,   3.70266935e-02,
          3.04973410e-03],
       [  2.89217017e-02,   7.00523427e-02,   3.77789301e-02,
          3.36683535e-03],
       [  3.37957806e-02,   6.46219284e-02,   3.69993789e-02,
          3.12424144e-03],
       [  4.38895998e-02,   6.19067212e-02,   3.75360971e-02,
          3.53168748e-03],
       [  4.89965903e-02,   5.75623939e-02,   3.96330016e-02,
          3.74489976e-03],
       [  5.20271204e-02,   5.43041432e-02,   4.00944601e-02,
          3.84206848e-03],
       [  5.90529667e-02,   5.05028542e-02,   4.22605183e-02,
          3.71159179e-03],
       [  7.15537761e-02,   4.72446036e-02,   4.25519467e-02,
          4.31928618e-03],
       [  6.15866430e-02,   6.24497647e-02,   4.40948626e-02,
          3.69655119e-03],
       [  7.47510231e-02,   6.19067212e-02,   4.66305718e-02,
          4.35641968e-03],
       [  8.97037671e

In [199]:
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=12)

<h4>Ensemble 1: Adaboost

In [211]:
from sklearn.cross_validation import cross_val_score
from sklearn.ensemble import AdaBoostRegressor



In [212]:

clf = AdaBoostRegressor(n_estimators=20)
clf.fit(X, y)
#clf.score(X_test,y_test)

/Users/rajkirangaddati/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
         n_estimators=20, random_state=None)

In [213]:
meanS=cross_val_score(clf,X_train,y_train)

/Users/rajkirangaddati/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/rajkirangaddati/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Users/rajkirangaddati/anaconda/lib/python2.7/site-packages/sklearn/utils/validation.py:449: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [214]:
meanS.mean()

0.82443740264344656

In [215]:
data2=pd.read_csv("/Users/rajkirangaddati/Documents/Submission File.csv")
X_test=data2[[u'GDP Per Capita (USD)', u'Youth unemployment rate (%)',
       u'Energy Production (Quadrillion Btu)',
       u'High-technology exports (current US$)']].values
normalize(X_test, norm='l2', axis=0, copy=False)
y_test=clf.predict(X_test)

In [217]:
y_test.reshape(26,1)

array([[ 13611.87969543],
       [ 13611.87969543],
       [ 13611.87969543],
       [ 13611.87969543],
       [ 13454.95703043],
       [ 12888.1614677 ],
       [ 12888.1614677 ],
       [ 12888.1614677 ],
       [ 12888.1614677 ],
       [ 12868.59353079],
       [ 12888.1614677 ],
       [ 12888.1614677 ],
       [ 11898.56376271],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13486.153365  ],
       [ 13663.9867263 ]])

<p>Good score but the predictions seem to be off.

<h3>The winner: An Ensemble: Random Forest Regression

In [225]:
from sklearn.ensemble import RandomForestRegressor as r

In [219]:
clfR = r()
clfR.fit(X, y)
#scores.mean()

/Users/rajkirangaddati/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  from ipykernel import kernelapp as app


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
           verbose=0, warm_start=False)

In [221]:
y_testR=clfR.predict(X_test)

In [222]:
y_testR.reshape(26,1)

array([[ 14041.447077 ],
       [ 14041.447077 ],
       [ 13128.350619 ],
       [ 13128.350619 ],
       [ 12181.490086 ],
       [ 13041.9783568],
       [ 12127.9927782],
       [ 13074.8533112],
       [ 13074.8533112],
       [ 12872.3631872],
       [ 13488.011922 ],
       [ 12925.860495 ],
       [  8411.4909727],
       [ 15770.607651 ],
       [ 15770.607651 ],
       [ 15770.607651 ],
       [ 15612.727064 ],
       [ 15613.324581 ],
       [ 15613.324581 ],
       [ 15589.183267 ],
       [ 15550.991835 ],
       [ 15588.58575  ],
       [ 15419.008357 ],
       [ 15588.58575  ],
       [ 15589.183267 ],
       [ 16467.247487 ]])

<p>This result was pasted into excel.